### PR TITLE
 fix negative temperature handling

### LINKED ISSUE #2: Negative temperatures are actually sign-magnitude
Temperature value is returned in sign-magnitude form, but code here assumes two-'s complement. See similar issue in the CircuitPython library: https://github.com/adafruit/Adafruit_CircuitPython_AM2320/issues/1

### PR DESCRIPTION
**Pull request by jerryneedell**
fixes #2  - tested by placing sensor in freezer

```
Hum: 20.10
Temp: 0.30
Hum: 20.20
Temp: 0.10
Hum: 20.30
Temp: 0.10
Hum: 20.50
Temp: 0.00
Hum: 20.60
Temp: -0.30
Hum: 20.70
Temp: -0.40
Hum: 20.80
Temp: -0.60
Hum: 20.90
Temp: -0.50

```

### CODE REVIEW

File: Adafruit_AM2320.cpp [hunk 1]
```diff
@@ -84,9 +84,15 @@ bool Adafruit_AM2320::begin() {
 /**************************************************************************/
 float Adafruit_AM2320::readTemperature() {
   uint16_t t = readRegister16(AM2320_REG_TEMP_H);
+  float ft;
   if (t == 0xFFFF) return NAN;
-
-  float ft = (int16_t)t;
+  // check sign bit - the temperature mSB is signd , bit 0-15 are mignitude
+  if(t >= 32768){
```
Comment (dhalbert) [inline Adafruit_AM2320.cpp]: how about `if (t & 0x8000)` to make it clear it's a bit check?

Comment (jerryneedell) [reply Adafruit_AM2320.cpp]: sounds good - will implement

**Comment by jerryneedell** [comment]
tested latest PR in freezer:
```
Temp: 0.50
Hum: 28.00
Temp: 0.50
Hum: 28.20
Temp: 0.30
Hum: 28.30
Temp: 0.40
Hum: 28.50
Temp: 0.10
Hum: 28.60
Temp: 0.10
Hum: 28.70
Temp: -0.10
Hum: 28.80
Temp: -0.20
Hum: 28.90
Temp: -0.30
Hum: 29.00
Temp: -0.40
Hum: 29.10
Temp: -0.30
Hum: 29.30
Temp: -0.60
Hum: 29.40
Temp: -0.70
Hum: 29.60
```
